#!/bin/bash
mkdir -p ~/.jupyter
for file in .jupyter/*; do
    dest=~/.jupyter/$(basename "$file")
    if [ ! -e "$dest" ]; then
        cp "$file" "$dest"
    else
        echo "Skipping $(basename "$file"), already exists."
    fi
done
